metadata:
    train_path: "metadata/ser_train_multiple_languages.csv"
    dev_path: "metadata/ser_dev_coraa.csv"
    audio_path_column: "wav_file"
    label_column: "label"

data:
    base_dir: ""
    target_sampling_rate: 16000
    apply_dbfs_norm: true
    target_dbfs: -31.187887972911266
    pad_audios: true
    apply_augmentation: true
    audio_augmentator: [
        {
            "name": "pitch_shift",
            "min_semitones": -3,
            "max_semitones": 3,
            "p": 0.25 # propability of apply this method, 0 is disable
        },
        {
            "name": "gaussian",
            "min_amplitude": 0.0001,
            "max_amplitude": 0.001,
            "p": 0.25 # propability of apply this method, 0 is disable
        }
    ]

train:
    model_checkpoint: "facebook/wav2vec2-xls-r-300m"
    weights_output_path: 'checkpoints/${logging.run_name}/train'
    seed: 42
    epochs: 10
    metric: "f1"
    batch_size: 2
    num_workers: 8
    warmup_ratio: 0.1
    logging_steps: 10
    learning_rate: 0.00003
    save_total_limit: 2
    use_early_stop: False
    early_stop_epochs: 10
    gradient_accumulation_steps: 4

test:
    model_checkpoint: "./checkpoints/SE_shared_task-xls_r_300m-test-norm_dbfs-01/train"
    test_base_dir: "data/test"
    output_path: "results/pred.csv"
    batch_size: 4
    num_workers: 8

logging:
    run_name: "SE-wav2vec2_base-${data.apply_dbfs_norm}_norm-True_additional_data-False_iemocap-${train.epochs}_epochs_testing"